package simple;
/****
1.hashmap - complete map containing all the field name and length 
2.Added in the format "FieldName"+"Length"
3.Retreive the values by using .split("=")
*//////////
import java.io.*;
import java.util.*;
public class jana{
public static LinkedHashMap hashmap =new LinkedHashMap();
 //LinkedHashMap hashmap=new LinkedHashMap();
public static LinkedHashMap setValues(){ 
 LinkedHashMap hashmap1=null;
 LinkedHashMap hashmap2=null;
 LinkedHashMap hashmap3=null;
ArrayList list=null;
hashmap1=new LinkedHashMap();
 hashmap2=new LinkedHashMap();
 hashmap3=new LinkedHashMap();
list=new ArrayList();
list.add("6 1");
list.add("6 2");
hashmap3.put("6",list);
list=new ArrayList();
list.add("7 1");
list.add("7 2");
hashmap3.put("7",list);
list=new ArrayList();
list.add("8 1");
list.add("8 2");
hashmap3.put("8",list);
hashmap2.put("11",hashmap3);
 hashmap3=new LinkedHashMap();
list=new ArrayList();
list.add("6 1");
list.add("6 2");
hashmap3.put("6",list);
list=new ArrayList();
list.add("7 1");
list.add("7 2");
hashmap3.put("7",list);
list=new ArrayList();
list.add("8 1");
list.add("8 2");
hashmap3.put("8",list);
hashmap2.put("12",hashmap3);
 hashmap3=new LinkedHashMap();
list=new ArrayList();
list.add("6 1");
list.add("6 2");
hashmap3.put("6",list);
list=new ArrayList();
list.add("7 1");
list.add("7 2");
hashmap3.put("7",list);
list=new ArrayList();
list.add("8 1");
list.add("8 2");
hashmap3.put("8",list);
hashmap2.put("13",hashmap3);
 hashmap3=new LinkedHashMap();
list=new ArrayList();
list.add("6 1");
list.add("6 2");
hashmap3.put("6",list);
list=new ArrayList();
list.add("7 1");
list.add("7 2");
hashmap3.put("7",list);
list=new ArrayList();
list.add("8 1");
list.add("8 2");
hashmap3.put("8",list);
hashmap2.put("14",hashmap3);
hashmap1.put("16",hashmap2);
 hashmap2=new LinkedHashMap();
 hashmap3=new LinkedHashMap();
list=new ArrayList();
list.add("6 1");
list.add("6 2");
hashmap3.put("6",list);
list=new ArrayList();
list.add("7 1");
list.add("7 2");
hashmap3.put("7",list);
list=new ArrayList();
list.add("8 1");
list.add("8 2");
hashmap3.put("8",list);
hashmap2.put("11",hashmap3);
 hashmap3=new LinkedHashMap();
list=new ArrayList();
list.add("6 1");
list.add("6 2");
hashmap3.put("6",list);
list=new ArrayList();
list.add("7 1");
list.add("7 2");
hashmap3.put("7",list);
list=new ArrayList();
list.add("8 1");
list.add("8 2");
hashmap3.put("8",list);
hashmap2.put("12",hashmap3);
 hashmap3=new LinkedHashMap();
list=new ArrayList();
list.add("6 1");
list.add("6 2");
hashmap3.put("6",list);
list=new ArrayList();
list.add("7 1");
list.add("7 2");
hashmap3.put("7",list);
list=new ArrayList();
list.add("8 1");
list.add("8 2");
hashmap3.put("8",list);
hashmap2.put("13",hashmap3);
 hashmap3=new LinkedHashMap();
list=new ArrayList();
list.add("6 1");
list.add("6 2");
hashmap3.put("6",list);
list=new ArrayList();
list.add("7 1");
list.add("7 2");
hashmap3.put("7",list);
list=new ArrayList();
list.add("8 1");
list.add("8 2");
hashmap3.put("8",list);
hashmap2.put("14",hashmap3);
hashmap1.put("17",hashmap2);
 hashmap2=new LinkedHashMap();
 hashmap3=new LinkedHashMap();
list=new ArrayList();
list.add("6 1");
list.add("6 2");
hashmap3.put("6",list);
list=new ArrayList();
list.add("7 1");
list.add("7 2");
hashmap3.put("7",list);
list=new ArrayList();
list.add("8 1");
list.add("8 2");
hashmap3.put("8",list);
hashmap2.put("11",hashmap3);
 hashmap3=new LinkedHashMap();
list=new ArrayList();
list.add("6 1");
list.add("6 2");
hashmap3.put("6",list);
list=new ArrayList();
list.add("7 1");
list.add("7 2");
hashmap3.put("7",list);
list=new ArrayList();
list.add("8 1");
list.add("8 2");
hashmap3.put("8",list);
hashmap2.put("12",hashmap3);
 hashmap3=new LinkedHashMap();
list=new ArrayList();
list.add("6 1");
list.add("6 2");
hashmap3.put("6",list);
list=new ArrayList();
list.add("7 1");
list.add("7 2");
hashmap3.put("7",list);
list=new ArrayList();
list.add("8 1");
list.add("8 2");
hashmap3.put("8",list);
hashmap2.put("13",hashmap3);
 hashmap3=new LinkedHashMap();
list=new ArrayList();
list.add("6 1");
list.add("6 2");
hashmap3.put("6",list);
list=new ArrayList();
list.add("7 1");
list.add("7 2");
hashmap3.put("7",list);
list=new ArrayList();
list.add("8 1");
list.add("8 2");
hashmap3.put("8",list);
hashmap2.put("14",hashmap3);
hashmap1.put("18",hashmap2);
hashmap.put("21",hashmap1);
hashmap1=new LinkedHashMap();
 hashmap2=new LinkedHashMap();
 hashmap3=new LinkedHashMap();
list=new ArrayList();
list.add("6 1");
list.add("6 2");
hashmap3.put("6",list);
list=new ArrayList();
list.add("7 1");
list.add("7 2");
hashmap3.put("7",list);
list=new ArrayList();
list.add("8 1");
list.add("8 2");
hashmap3.put("8",list);
hashmap2.put("11",hashmap3);
 hashmap3=new LinkedHashMap();
list=new ArrayList();
list.add("6 1");
list.add("6 2");
hashmap3.put("6",list);
list=new ArrayList();
list.add("7 1");
list.add("7 2");
hashmap3.put("7",list);
list=new ArrayList();
list.add("8 1");
list.add("8 2");
hashmap3.put("8",list);
hashmap2.put("12",hashmap3);
 hashmap3=new LinkedHashMap();
list=new ArrayList();
list.add("6 1");
list.add("6 2");
hashmap3.put("6",list);
list=new ArrayList();
list.add("7 1");
list.add("7 2");
hashmap3.put("7",list);
list=new ArrayList();
list.add("8 1");
list.add("8 2");
hashmap3.put("8",list);
hashmap2.put("13",hashmap3);
 hashmap3=new LinkedHashMap();
list=new ArrayList();
list.add("6 1");
list.add("6 2");
hashmap3.put("6",list);
list=new ArrayList();
list.add("7 1");
list.add("7 2");
hashmap3.put("7",list);
list=new ArrayList();
list.add("8 1");
list.add("8 2");
hashmap3.put("8",list);
hashmap2.put("14",hashmap3);
hashmap1.put("16",hashmap2);
 hashmap2=new LinkedHashMap();
 hashmap3=new LinkedHashMap();
list=new ArrayList();
list.add("6 1");
list.add("6 2");
hashmap3.put("6",list);
list=new ArrayList();
list.add("7 1");
list.add("7 2");
hashmap3.put("7",list);
list=new ArrayList();
list.add("8 1");
list.add("8 2");
hashmap3.put("8",list);
hashmap2.put("11",hashmap3);
 hashmap3=new LinkedHashMap();
list=new ArrayList();
list.add("6 1");
list.add("6 2");
hashmap3.put("6",list);
list=new ArrayList();
list.add("7 1");
list.add("7 2");
hashmap3.put("7",list);
list=new ArrayList();
list.add("8 1");
list.add("8 2");
hashmap3.put("8",list);
hashmap2.put("12",hashmap3);
 hashmap3=new LinkedHashMap();
list=new ArrayList();
list.add("6 1");
list.add("6 2");
hashmap3.put("6",list);
list=new ArrayList();
list.add("7 1");
list.add("7 2");
hashmap3.put("7",list);
list=new ArrayList();
list.add("8 1");
list.add("8 2");
hashmap3.put("8",list);
hashmap2.put("13",hashmap3);
 hashmap3=new LinkedHashMap();
list=new ArrayList();
list.add("6 1");
list.add("6 2");
hashmap3.put("6",list);
list=new ArrayList();
list.add("7 1");
list.add("7 2");
hashmap3.put("7",list);
list=new ArrayList();
list.add("8 1");
list.add("8 2");
hashmap3.put("8",list);
hashmap2.put("14",hashmap3);
hashmap1.put("17",hashmap2);
 hashmap2=new LinkedHashMap();
 hashmap3=new LinkedHashMap();
list=new ArrayList();
list.add("6 1");
list.add("6 2");
hashmap3.put("6",list);
list=new ArrayList();
list.add("7 1");
list.add("7 2");
hashmap3.put("7",list);
list=new ArrayList();
list.add("8 1");
list.add("8 2");
hashmap3.put("8",list);
hashmap2.put("11",hashmap3);
 hashmap3=new LinkedHashMap();
list=new ArrayList();
list.add("6 1");
list.add("6 2");
hashmap3.put("6",list);
list=new ArrayList();
list.add("7 1");
list.add("7 2");
hashmap3.put("7",list);
list=new ArrayList();
list.add("8 1");
list.add("8 2");
hashmap3.put("8",list);
hashmap2.put("12",hashmap3);
 hashmap3=new LinkedHashMap();
list=new ArrayList();
list.add("6 1");
list.add("6 2");
hashmap3.put("6",list);
list=new ArrayList();
list.add("7 1");
list.add("7 2");
hashmap3.put("7",list);
list=new ArrayList();
list.add("8 1");
list.add("8 2");
hashmap3.put("8",list);  
hashmap2.put("13",hashmap3);
 hashmap3=new LinkedHashMap();
list=new ArrayList();
list.add("6 1");
list.add("6 2");
hashmap3.put("6",list);
list=new ArrayList();
list.add("7 1");
list.add("7 2");
hashmap3.put("7",list);
list=new ArrayList();
list.add("8 1");
list.add("8 2");
hashmap3.put("8",list);
hashmap2.put("14",hashmap3);
hashmap1.put("18",hashmap2);
hashmap.put("22",hashmap1);
return hashmap;
}
}